<a href="https://colab.research.google.com/github/roopak5/NUmpy_Pandas-Assignment/blob/main/Assignment_PANDAS_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Generate an array of zeroes using inbuilt numpy function.


In [ ]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

2) Run the given code and find the dot product of both arrays.


In [ ]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[6 3 3 6]
 [6 8 5 3]
 [5 9 6 4]]
[[3 6 2]
 [6 4 3]
 [8 5 7]
 [4 9 5]]


In [ ]:
a.dot(b)


array([[ 84, 117,  72],
       [118, 120,  86],
       [133, 132,  99]])

#Your code here


In [ ]:
b.dot(a)

array([[ 64,  75,  51,  44],
       [ 75,  77,  56,  60],
       [113, 127,  91,  91],
       [103, 129,  87,  71]])

3)Read the csv file provided using pandas and display the first 5 entries


In [ ]:
import pandas as pd

data = pd.read_csv('/content/data.csv')
data.head(5)

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

4)Describe the data with all features.

In [ ]:
#df = pd.DataFrame(data)
#df.describe()
feature = data.describe()
feature

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

5)Find the total count of missing values for each feature.


In [ ]:
data.apply(lambda feature: feature.count())


OBJECTID       25
UNIT_NAME      25
DESCRIPTION    25
ACRES          25
SHAPE.AREA     25
SHAPE.LEN      25
dtype: int64

6)Display all the unique values from the 'DESCRIPTION’ column.


In [ ]:
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.


In [ ]:
df = data.groupby(['DESCRIPTION']).agg([len,min])
df

OBJECTID     UNIT_NAME  \
                           len min       len   
DESCRIPTION                                    
Interpretive Center          1  29         1   
State Natural Area           2  37         2   
State Nature Preserve        2  39         2   
State Park                  13  21        13   
State Recreation Area        7  30         7   

                                                            ACRES          \
                                                        min   len     min   
DESCRIPTION                                                                 
Interpretive Center     Lewis and Clark Interpretive Center     1   14.71   
State Natural Area               Elkhorn State Natural Area     2  174.39   
State Nature Preserve       Gunlogson State Nature Preserve     2   72.30   
State Park                           Beaver Lake State Park    13   63.03   
State Recreation Area  Butte St. Paul State Recreation Area     7   11.40   

                      SHAPE.AREA           SHAPE.LEN            
                             len       min       len       min  
DESCRIPTION                                                     
Interpretive Center            1  0.000007         1  0.016774  
State Natural Area             2  0.000083         2  0.067082  
State Nature Preserve          2  0.000034         2  0.033885  
State Park                    13  0.000030        13  0.024016  
State Recreation Area          7  0.000005         7  0.009396


8)Generate a random sample of 10 rows from the data.


In [ ]:
df = int(np.random.randint(0,len(data) -10))
df

13

In [ ]:
data.iloc[df:df+10, :]

OBJECTID                                   UNIT_NAME  \
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  
13  State Recreation Area   247.11    0.000120   0.050518  
14             State Park   775.28    0.000378   0.145220  
15             State Park   739.52    0.000357   0.191806  
16     State Natural Area   264.84    0.000127   0.067082  
17  State Recreation Area    21.56    0.000010   0.013294  
18  State Nature Preserve    95.89    0.000048   0.040465  
19  State Nature Preserve    72.30    0.000034   0.033885  
20     State Natural Area   174.39    0.000083   0.087192  
21  State Recreation Area  1236.98    0.000615   0.338800  
22  State Recreation Area   695.04    0.000345   0.086487

9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.


In [ ]:
New_feature = np.random.rand(25,1)
data['New_feature'] = New_feature
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New_feature  
0              State Park   586.48    0.000284   0.135641     0.652682  
1              State Park   273.16    0.000129   0.080067     0.674077  
2              State Park   836.47    0.000399   0.119868     0.666699  
3              State Park   933.78    0.000444   0.128733     0.460939  
4              State Park   959.33    0.000469   0.125546     0.945452  
5              State Park   930.30    0.000461   0.166712     0.135368  
6              State Park  1508.53    0.000751   0.212196     0.968506  
7              State Park   524.81    0.000256   0.130420     0.447623  
8     Interpretive Center    14.71    0.000007   0.016774     0.342112  
9   State Recreation Area    11.40    0.000005   0.009396     0.730170  
10             State Park  6492.93    0.003136   0.313756     0.384689  
11             State Park    63.03    0.000030   0.024016     0.434918  
12  State Recreation Area    51.23    0.000025   0.022095     0.895906  
13  State Recreation Area   247.11    0.000120   0.050518     0.292537  
14             State Park   775.28    0.000378   0.145220     0.154246  
15             State Park   739.52    0.000357   0.191806     0.208619  
16     State Natural Area   264.84    0.000127   0.067082     0.666269  
17  State Recreation Area    21.56    0.000010   0.013294     0.365064  
18  State Nature Preserve    95.89    0.000048   0.040465     0.690487  
19  State Nature Preserve    72.30    0.000034   0.033885     0.994702  
20     State Natural Area   174.39    0.000083   0.087192     0.606172  
21  State Recreation Area  1236.98    0.000615   0.338800     0.150488  
22  State Recreation Area   695.04    0.000345   0.086487     0.173614  
23             State Park   569.07    0.000274   0.180257     0.675312  
24  State Recreation Area    25.22    0.000013   0.026357     0.499203

10) Replace zero value of column 'OBJECTID' with mean value permanently.


In [ ]:
np.mean(data.OBJECTID)

33.0

In [ ]:
data['OBJECTID']=data['OBJECTID'].replace(33,35)
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        35                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New_feature  
0              State Park   586.48    0.000284   0.135641     0.652682  
1              State Park   273.16    0.000129   0.080067     0.674077  
2              State Park   836.47    0.000399   0.119868     0.666699  
3              State Park   933.78    0.000444   0.128733     0.460939  
4              State Park   959.33    0.000469   0.125546     0.945452  
5              State Park   930.30    0.000461   0.166712     0.135368  
6              State Park  1508.53    0.000751   0.212196     0.968506  
7              State Park   524.81    0.000256   0.130420     0.447623  
8     Interpretive Center    14.71    0.000007   0.016774     0.342112  
9   State Recreation Area    11.40    0.000005   0.009396     0.730170  
10             State Park  6492.93    0.003136   0.313756     0.384689  
11             State Park    63.03    0.000030   0.024016     0.434918  
12  State Recreation Area    51.23    0.000025   0.022095     0.895906  
13  State Recreation Area   247.11    0.000120   0.050518     0.292537  
14             State Park   775.28    0.000378   0.145220     0.154246  
15             State Park   739.52    0.000357   0.191806     0.208619  
16     State Natural Area   264.84    0.000127   0.067082     0.666269  
17  State Recreation Area    21.56    0.000010   0.013294     0.365064  
18  State Nature Preserve    95.89    0.000048   0.040465     0.690487  
19  State Nature Preserve    72.30    0.000034   0.033885     0.994702  
20     State Natural Area   174.39    0.000083   0.087192     0.606172  
21  State Recreation Area  1236.98    0.000615   0.338800     0.150488  
22  State Recreation Area   695.04    0.000345   0.086487     0.173614  
23             State Park   569.07    0.000274   0.180257     0.675312  
24  State Recreation Area    25.22    0.000013   0.026357     0.499203

In [ ]:
#data['DESCRIPTION']= data['DESCRIPTION'].replace('State Park', 'Park')
data['DESCRIPTION']= data['DESCRIPTION'].replace(data.iloc[1,4], 'reply')
data
#data.drop(data.iloc[:,-1])

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        35                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New_feature  
0              State Park   586.48    0.000284   0.135641     0.652682  
1              State Park   273.16    0.000129   0.080067     0.674077  
2              State Park   836.47    0.000399   0.119868     0.666699  
3              State Park   933.78    0.000444   0.128733     0.460939  
4              State Park   959.33    0.000469   0.125546     0.945452  
5              State Park   930.30    0.000461   0.166712     0.135368  
6              State Park  1508.53    0.000751   0.212196     0.968506  
7              State Park   524.81    0.000256   0.130420     0.447623  
8     Interpretive Center    14.71    0.000007   0.016774     0.342112  
9   State Recreation Area    11.40    0.000005   0.009396     0.730170  
10             State Park  6492.93    0.003136   0.313756     0.384689  
11             State Park    63.03    0.000030   0.024016     0.434918  
12  State Recreation Area    51.23    0.000025   0.022095     0.895906  
13  State Recreation Area   247.11    0.000120   0.050518     0.292537  
14             State Park   775.28    0.000378   0.145220     0.154246  
15             State Park   739.52    0.000357   0.191806     0.208619  
16     State Natural Area   264.84    0.000127   0.067082     0.666269  
17  State Recreation Area    21.56    0.000010   0.013294     0.365064  
18  State Nature Preserve    95.89    0.000048   0.040465     0.690487  
19  State Nature Preserve    72.30    0.000034   0.033885     0.994702  
20     State Natural Area   174.39    0.000083   0.087192     0.606172  
21  State Recreation Area  1236.98    0.000615   0.338800     0.150488  
22  State Recreation Area   695.04    0.000345   0.086487     0.173614  
23             State Park   569.07    0.000274   0.180257     0.675312  
24  State Recreation Area    25.22    0.000013   0.026357     0.499203

In [ ]:
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  New_feature  
0   0.135641     0.652682  
1   0.080067     0.674077  
2   0.119868     0.666699  
3   0.128733     0.460939  
4   0.125546     0.945452

In [ ]:
#def add(a,b):
#  return a+b

In [ ]:
#add(5,6)

In [ ]:
#add_num=lambda x,y: x+y

In [ ]:
#add_num(4,5)